### PR TITLE
Preliminary FDS input files and output files for sbi.

### PR DESCRIPTION
**Pull request by drjfloyd**

### CODE REVIEW

**Comment by rmcdermo** [comment]
Jason,
I'm fine with using FSRI as the institute here.  I think it's understood that we are on the same team.  I think it's easier to have compact names for legends, etc.  If you make anymore PRs feel free to change that.

**Comment by drjfloyd** [comment]
Will do.

**Comment by rmcdermo** [comment]
Also, please try to add your scripts to Actions for Fire_Growth?  Go to `.github/workflows` and edit the `Fire_Growth.yml` file.  Follow Kevin's example.  I'm happy to help if you get stuck.  Thanks

This will then create a zip with all your plots to add to the SCRIPT_FIGURES release page.

**Comment by drjfloyd** [comment]
Haven't started on plotting yet. Next step now that I have organized files. Looks like it should be easy enough to modify Kevin's stuff.

**Pull request merged**
