### PR TITLE
Create readme.md

### PR DESCRIPTION
**Pull request by ejweckman**
I think this is the correct format for the explanation of the Waterloo pan burner facility.

### CODE REVIEW

**Comment by rmcdermo** [comment]
Hi Beth,
Why did you close the pull request?  We can always make mods to it later.  Let me know if I can help.
Cheers,
Randy

**Comment by ejweckman** [comment]
Hi Randy
Because I am still trying to figure Github out - sorry! I was so close to getting the documentation up there (I think even in the right format) too...
Is there a way to reopen what I did or do I do it again - no worries either way but will try to do it right - LOL!
Beth

From: Randy McDermott
Sent: Saturday, January 30, 2016 4:05 PM
To: MaCFP/macfp-db
Reply To: MaCFP/macfp-db
Cc: Beth Weckman
Subject: Re: [macfp-db] Create readme.md (#3)



Hi Beth,
Why did you close the pull request? We can always make mods to it later. Let me know if I can help.
Cheers,
Randy

**Comment by rmcdermo** [comment]
Sure, I can reopen and merge it in!  Just give me the word.

**Comment by ejweckman** [comment]
Text was all done - have to load the png file - which is what I was trying to do when I close the request...
So yes you can merge but it is missing the picture file and the data -- learning Github as I go I am afraid,
Beth

From: Randy McDermott
Sent: Saturday, January 30, 2016 4:09 PM
To: MaCFP/macfp-db
Reply To: MaCFP/macfp-db
Cc: Beth Weckman
Subject: Re: [macfp-db] Create readme.md (#3)



Sure, I can reopen and merge it in! Just give me the word.

**Comment by rmcdermo** [comment]
Go ahead and get things as you like them with the png, etc.  And then
submit a new pull request.  Otherwise Git will complain if you are not
completely up to date when you try to send the request.  You are doing
great!  Git is not easy to learn, I know from experience!

**Comment by ejweckman** [comment]
Haha - if only I knew how to bring in a png file -- I think this one has me stumped!
Beth

From: Randy McDermott
Sent: Saturday, January 30, 2016 4:20 PM
To: MaCFP/macfp-db
Reply To: MaCFP/macfp-db
Cc: Beth Weckman
Subject: Re: [macfp-db] Create readme.md (#3)


Go ahead and get things as you like them with the png, etc. And then
submit a new pull request. Otherwise Git will complain if you are not
completely up to date when you try to send the request. You are doing
great! Git is not easy to learn, I know from experience!

**Comment by rmcdermo** [comment]
OK, no problem.  How about I reopen and merge the README file and you send
me an email with the png and I'll add it?

**Comment by ejweckman** [comment]
That sounds awesome to me!  Sometime I would love to know but apparently I am .png limited today :).  I have attached the file...
I have to race off for a previous commitment.  Will get back to uploading the data files later tonight if all goes as planned - else tomorrow...

Thank you!!!
Beth Weckman

Professor
Fire Research Lab
University of Waterloo
Waterloo, ON N2L 3G1

519-888-4567  x 33345
ejweckman@uwaterloo.ca

________________________________________

**Pull request merged**
