### PR TITLE
UNSW results 

### PR DESCRIPTION
**Pull request by hong27**

### CODE REVIEW

**Comment by rmcdermo** [comment]
@hong27 There are a couple of problems with this PR.  First, it looks like you did not update your repository to the last prior to committing your yml files.  There were several other submissions yesterday, and so you have conflicts you need to resolove.

Second, you have a commit where you are removing a `__pycache__` folder.  This is not under version control, so I can only assume you accidentally added and then removed this by mistake.  This is not something we can merge to the main repo.

So, I suggest your proceed by:
1. Save all your modified files to a safe place (desktop)
2. Reset your fork to a commit prior to the `__pycache__` mistake (if you need help with this, let me know; the alternative is the delete your fork and refork the main repo)
3. Update your local rep and fork on GitHub
4. Put your files back and commit them and send your PR

Thanks!

**Comment by hong27** [comment]
@rmcdermo Thanks Randy, I am sorry for the inconvenience caused. I used git rebase to resolve this problem. It seems to be able to automatically merge now, so I assumed it is fine now. If there is still an issue, please let me know, and I will fix it soon. Thanks for your help.

**Comment by rmcdermo** [comment]
Hi @hong27 .  Sorry, there is still a problem.  I am being picky at this point about adding files because I have many, many people sending PRs and I do not want anything to break.  So, as I asked, please reset to a clean main repo and add your files in one commit.

**Comment by hong27** [comment]
@rmcdermo I have created a new fork and now it only has one commit. I hope it goes well but if not please let me know and I will address it promptly when I wake up. Apologies for being not skilled in managing Git repos. Thanks for your help.

**Pull request closed without merging**
