### PR TITLE
FM Vertical Wall Flames: Commit preliminary NIST results and scripts.

### PR DESCRIPTION
**Pull request by mcgratta**
I checked that the script worked successfully on my results.

### CODE REVIEW

**Comment by rmcdermo** [comment]
Thanks, Kevin!

**Comment by rmcdermo** [comment]
@mcgratta 
Can you also add the model questionnaire when you get a chance?  Thanks.

https://github.com/MaCFP/macfp-db/blob/master/Utilities/model_questionnaire.md

**Comment by rmcdermo** [comment]
The questionnaire should live in the same directory as the computational results.  See the UGent results as an example.

https://github.com/MaCFP/macfp-db/tree/master/Gaseous_Pool_Fires/Sandia_Flames/Computational_Results/2017/UGent

**Comment by mcgratta** [comment]
Yup -- I just wanted to commit what I have so far.

**Pull request merged**
